Update gitlab-ci.yml

diff --git a/gitlab-ci.yml b/gitlab-ci.yml
--- a/gitlab-ci.yml
+++ b/gitlab-ci.yml
@@ -1,4 +1,5 @@
 stages:
+  - init
   - build
   - test
   - sast
@@ -12,9 +13,8 @@ variables:
   SEARCH_MAX_DEPTH: 10
   PACKAGE_NAME: "sample"
   PACKAGE_VERSION: "0.0.1-SNAPSHOT"
-  COMMIT_TAG: "${CI_COMMIT_SHA:0:4}" # Extract last 4 characters of the commit hash dynamically
   PACKAGE_REGISTRY_URL: "https://gitlab.com/api/v4/projects/38062833/packages/generic"
-  CI_COMMIT_TAG: "abcd"
+
 
 # Cache definitions
 cache:
@@ -22,6 +22,19 @@ cache:
   paths:
     - .m2/repository/
     - target/
+
+stages:
+  - init # initializing some variables for deployment
+tag:
+  stage: init
+  script:
+    - PACKAGE_VERSION=$(echo $CI_COMMIT_SHA | cut -c -4)
+    - echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> build.env
+  artifacts:
+    expire_in: 1 days
+    reports:
+      dotenv: build.env
+
 
 # Build Stage
 build:
@@ -104,32 +117,11 @@ run-junit-tests:
   allow_failure: false
   needs: ["build", "send-reports"]
 
-# Tag Code Stage
-tag-code:
-  image: bitnami/git
-  stage: tagging
-  script:
-    - |
-      if [ -z "$CI_COMMIT_TAG" ]; then
-        echo "Error: Tagging is required. Please provide a tag."
-        exit 1
-      fi
 
-      # Configure Git user settings
-      echo "Configuring Git user settings..."
-      git config --global user.email "$GIT_USER_EMAIL"
-      git config --global user.name "$GIT_USERNAME"
 
-      # Tagging the code
-      echo "Tagging code with tag: $CI_COMMIT_TAG"
-      git tag -a "$CI_COMMIT_TAG" -m "Tagging code as $CI_COMMIT_TAG"
-
-      # Push the tag
-      echo "Pushing tag: $CI_COMMIT_TAG"
-      git push https://${GIT_USERNAME}:${GIT_PERSONAL_ACCESS_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git "$CI_COMMIT_TAG"
 
 # Tag Artifact Stage
-tag-artifact:
+tag-code:
   image: curlimages/curl:latest
   stage: tagging
   dependencies:
@@ -152,3 +144,31 @@ tag-artifact:
       curl --header "JOB-TOKEN: $CI_JOB_TOKEN" \
            --upload-file "target/sample-${CI_COMMIT_TAG}.jar" \
            "$PACKAGE_REGISTRY_URL/$PACKAGE_NAME/$PACKAGE_VERSION/sample-${CI_COMMIT_TAG}.jar"
+  only: 
+    - tags
+
+
+# Tag Artifact Stage
+tag-artifact:
+  image: curlimages/curl:latest
+  stage: tagging
+  dependencies:
+    - build
+  cache:
+    key: artifact-tagging-cache
+    paths:
+      - target/
+  script:
+    - |
+      if [ -z "$PACKAGE_VERSION" ]; then
+        echo "Error: Tagging is required before merging to main."
+        exit 1
+      fi
+
+      echo "Tagging artifact with tag: $PACKAGE_VERSION"
+      mv target/sample-0.0.1-SNAPSHOT.jar target/sample-${PACKAGE_VERSION}.jar
+
+      echo "Uploading artifact to package registry"
+      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" \
+           --upload-file "target/sample-${PACKAGE_VERSION}.jar" \
+           "$PACKAGE_REGISTRY_URL/$PACKAGE_NAME/$PACKAGE_VERSION/sample-${PACKAGE_VERSION}.jar"
